#!/bin/bash
. ./test_config.gitignore
MINERID="t01000"
[[ -z "$INDEX_ROOT_IPFS" ]] && { echo "INDEX_ROOT_IPFS is required"; exit 1; }
[[ -z "$MINERID" ]] && { echo "MINERID is required"; exit 1; }
[[ -z "$1" ]] && { echo "missing source path"; exit 1; }
[[ -z "$2" ]] && { echo "missing destination path"; exit 1; }
CMD="singularity-retrieve cp -p $MINERID singularity:/$INDEX_ROOT_IPFS/$1 $2"
# echo "$CMD"
$CMD
